# Generated by Django 4.2.23 on 2025-08-26 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipe',
            name='img',
            field=models.ImageField(upload_to='recipes'),
        ),
    ]
