# Generated by Django 4.2.23 on 2025-08-28 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veggie', '0002_alter_receipe_img'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Receipe',
            new_name='Recipe',
        ),
    ]
