# Generated by Django 4.2.23 on 2025-08-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggie', '0003_rename_receipe_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='img',
        ),
        migrations.AddField(
            model_name='recipe',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
