# Generated by Django 4.2.23 on 2025-08-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggie', '0004_remove_recipe_img_recipe_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='desc',
        ),
        migrations.AddField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
