# Generated by Django 4.2.23 on 2025-08-28 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veggie', '0006_alter_recipe_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='name',
            new_name='namer',
        ),
    ]
