# Generated by Django 4.2.23 on 2025-08-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggie', '0007_rename_name_recipe_namer'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='desc',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='img',
            field=models.ImageField(null=True, upload_to='recipes'),
        ),
    ]
